version: '3.6'

services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: beehive
            MYSQL_USER: Beehive
            MYSQL_PASSWORD: 123456
            ports: 
              -"8080:8080"
        volumes: 
           - ./docker_mysql_init.sql:/docker-entrypoint-initdb.d/docker_mysql_init.sql



    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080
